language: php
php:
    - 5.5
    - 5.6
services:
    - mysql
install:
    - composer install --no-interaction
before_script:
script:
    - bin/phpcs -p --standard=PSR2 --extensions=php ./src
    - bin/phpunit -c app
