<?php

namespace AppBundle\Repository;

/**
 * AchievementPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchievementPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
