<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * DrinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrinkRepository extends EntityRepository
{
    /**
     * @param \DateTime $from
     * @param \DateTime $to
     * @param User $user
     * @return array
     */
    public function findBetween(\DateTime $from, \DateTime $to, User $user)
    {
        $qb = $this->createQueryBuilder('d');
        $qb
            ->where('d.createdAt BETWEEN :from AND :to')
            ->andWhere('d.user = :user')
            ->setParameters(
                [
                    'from' => $from,
                    'to' => $to,
                    'user' => $user,
                ]
            );

        return $qb->getQuery()->getResult();
    }
}
