app:
    type:     rest
    prefix:   /api
    resource: "@AppBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    prefix:   /
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
