app:
    type:     rest
    prefix:   /api
    resource: "@AppBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    prefix:   /
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_security_login:
    pattern: /oauth/v2/auth_login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    pattern: /oauth/v2/auth_login_check
    defaults: { _controller: FOSUserBundle:Security:check }
