# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.repository.drink:
        class: AppBundle\Repository\DrinkRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle:Drink

    app.repository.achievement:
        class: AppBundle\Repository\AchievementRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle:Achievement

    app.repository.property:
        class: AppBundle\Repository\PropertyRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle:Property

    app.service.drink:
        class: AppBundle\Service\DrinkService
        arguments:
            - @app.repository.drink
            - @doctrine.orm.entity_manager

    app.service.achievement:
        class: AppBundle\Service\AchievementService
        arguments:
            - @app.repository.achievement

    app.service.property:
        class: AppBundle\Service\PropertyService
        arguments:
            - @app.repository.property
