app_api_achievements:
    type:     rest
    resource: "@AppBundle/Controller/AchievementsController.php"

app_api_drinks:
    type:     rest
    resource: "@AppBundle/Controller/DrinksController.php"

app_api_users:
    type:     rest
    resource: "@AppBundle/Controller/UsersController.php"
